---
name: 'About.com: Internet/Network Security'
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "6887"
url: https://raw.githubusercontent.com/api-network/organizations/main/about-com-internetnetwork-security.yaml
tags:
- Internet
apis: []
x-common:
- type: x-about
  url: https://www.lifewire.com/about-us
- type: x-about
  url: https://www.lifewire.com/about-us#EditorialGuidelines
- type: x-about
  url: https://www.lifewire.com/about-us#ContactUs
- type: x-blog
  url: https://www.lifewire.com/blogging-websites-4102605
- type: x-careers
  url: https://www.dotdash.com/careers/
- type: x-facebook
  url: http://www.facebook.com/lifewire
- type: x-privacy
  url: https://www.lifewire.com/safety-privacy-4102606
- type: x-privacy
  url: https://www.lifewire.com/protect-web-privacy-3901571
- type: x-support
  url: https://www.lifewire.com/getting-more-help-4102762
- type: x-terms-of-service
  url: https://www.lifewire.com/legal#privacy
- type: x-terms-of-service
  url: https://www.lifewire.com/legal#cookies-disclosure
- type: x-terms-of-service
  url: https://www.lifewire.com/legal#terms
- type: x-website
  url: https://netsecurity.about.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---