---
name: Application security solutions for Web, Mobile, and API-based applications
description: ""
image: https://s3.amazonaws.com/kinlane-productions2/api-evangelist-logos/api-evangelist-red-seal.png
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "0"
x-alexaRank: "20000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/application-security-solutions-for-web-mobile-and-apibased-applications.yaml
tags:
- Profile
apis: []
x-common:
- type: x-website
  url: http://www.cequence.ai
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---