---
name: Applications Technology (AppTek)
description: AppTek is an industry pioneer in artificial intelligence and machine
  learning-based automatic speech recognition, machine translation and natural language
  understanding technologies.
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "224891"
url: https://raw.githubusercontent.com/api-network/organizations/main/applications-technology-apptek.yaml
tags:
- Machine Translation
apis: []
x-common:
- type: x-developer
  url: http://developer.apptek.com
- type: x-facebook
  url: https://www.facebook.com/ApplicationsTechnology/
- type: x-linkedin
  url: https://www.linkedin.com/company/140785/
- type: x-twitter
  url: https://twitter.com/apptek_mclean?lang=en
- type: x-website
  url: https://www.apptek.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---