---
name: application-programming-interface.cioreview.com
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: ""
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/applicationprogramminginterface-cioreview-com.yaml
tags: []
apis: []
x-common:
- type: x-curated-source
  url: http://application-programming-interface.cioreview.com/vendor/2015/nexright
- type: x-website
  url: http://application-programming-interface.cioreview.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---