---
name: AWS Config
description: |-
  <p>AWS Config is a fully managed service that provides you with an AWS resource inventory, configuration history, and configuration change notifications to enable security and governance. Config Rules enables you to create rules that automatically check the configuration of AWS resources recorded by AWS Config.</p>
  <p>With AWS Config, you can discover existing and deleted AWS resources, determine your overall compliance against rules, and dive into configuration details of a resource at any point in time. These capabilities enable compliance auditing, security analysis, resource change tracking, and troubleshooting.</p>
image: http://kinlane-productions2.s3.amazonaws.com/api-evangelist-site/company/logos/Management-Tools_AWSConfig.png
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "10"
x-alexaRank: "14"
url: https://raw.githubusercontent.com/api-network/organizations/main/aws-config.yaml
tags:
- Security
- Relative Data
- Have API Paths
- Have API
- Governance
- Authentication
- Applications
- API Service Provider
- API Service Provider
- API Provider
- Amazon Web Services
apis: []
x-common:
- type: x-command-line-interface
  url: http://docs.aws.amazon.com/cli/latest/reference/configservice/index.html
- type: x-console
  url: https://console.aws.amazon.com/config
- type: x-documentation
  url: https://docs.aws.amazon.com/index.html?nc2=h_ql_doc
- type: x-documentation
  url: http://docs.aws.amazon.com/config/latest/APIReference/
- type: x-facebook
  url: https://www.facebook.com/amazonwebservices
- type: x-faq
  url: https://aws.amazon.com/config/faq/
- type: x-forums
  url: https://forums.aws.amazon.com/forum.jspa?forumID=184
- type: x-getting-started
  url: https://aws.amazon.com/config/getting-started/
- type: x-marketplace
  url: https://aws.amazon.com/marketplace/?nc2=h_ql_mp
- type: x-marketplace
  url: https://aws.amazon.com/marketplace/?nc2=h_mo
- type: x-partners
  url: https://aws.amazon.com/config/partners/
- type: x-press
  url: https://press.aboutamazon.com/press-releases/aws
- type: x-pricing
  url: https://aws.amazon.com/config/pricing/
- type: x-privacy
  url: https://aws.amazon.com/privacy/?nc1=f_pr
- type: x-security
  url: https://aws.amazon.com/blogs/security/tag/aws-config/
- type: x-support
  url: https://console.aws.amazon.com/support/home/?nc1=f_dr
- type: x-support
  url: https://console.aws.amazon.com/support/
- type: x-terms-of-service
  url: https://aws.amazon.com/terms/?nc1=f_pr
- type: x-tutorials
  url: https://aws.amazon.com/getting-started/tutorials/
- type: x-twitter
  url: https://twitter.com/awscloud
- type: x-website
  url: https://aws.amazon.com/config/
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---