---
name: Azure Automation
description: <p>Automate all of those frequent, time-consuming, and error-prone cloud
  management tasks. Azure Automation helps you focus on work that adds business value.
  By reducing errors and boosting efficiency, it also helps to lower your operational
  costs.</p>
image: http://kinlane-productions2.s3.amazonaws.com/api-evangelist-site/company/logos/azure-automation-save-time.png
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "10"
x-alexaRank: "33"
url: https://raw.githubusercontent.com/api-network/organizations/main/azure-automation.yaml
tags:
- Webhooks
- Relative Data
- Orchestration
- Microsoft
- Have API Paths
- Have API
- Automation
- API Service Provider
- API Provider
apis: []
x-common:
- type: x-blog
  url: https://azure.microsoft.com/en-us/blog/
- type: x-case-studies
  url: https://azure.microsoft.com/en-us/case-studies/
- type: x-code
  url: https://azure.microsoft.com/en-us/downloads/?sdk=net
- type: x-documentation
  url: https://docs.microsoft.com/en-us/azure/automation/
- type: x-documentation
  url: https://docs.microsoft.com/en-us/azure/
- type: x-documentation
  url: https://docs.microsoft.com/en-us/learn/azure/
- type: x-documentation
  url: https://docs.microsoft.com/en-us/azure/automation
- type: x-events
  url: https://azure.microsoft.com/en-us/community/events/
- type: x-facebook
  url: https://www.facebook.com/microsoftazure
- type: x-feed
  url: https://azurecomcdn.azureedge.net/en-us/blog/feed/
- type: x-linkedin
  url: https://www.linkedin.com/company/16188386
- type: x-marketplace
  url: https://azuremarketplace.microsoft.com/
- type: x-open-source
  url: https://azure.microsoft.com/en-us/services/openshift/
- type: x-partner
  url: https://azure.microsoft.com/en-us/partners/
- type: x-partner
  url: https://azure.com/partners
- type: x-pricing
  url: https://azure.microsoft.com/en-us/pricing/details/automation/
- type: x-pricing
  url: https://azure.microsoft.com/en-us/pricing/
- type: x-pricing
  url: https://azure.microsoft.com/en-us/pricing/calculator/
- type: x-security
  url: https://azure.microsoft.com/en-us/services/#security
- type: x-service-level-agreement
  url: https://azure.microsoft.com/en-us/support/legal/sla/automation/
- type: x-status
  url: https://azure.microsoft.com/en-us/status/
- type: x-status
  url: https://status.azure.com
- type: x-status
  url: https://status.azure.com/
- type: x-support
  url: https://azure.microsoft.com/en-us/support/options/
- type: x-support
  url: https://azure.microsoft.com/en-us/support/plans/
- type: x-support
  url: https://azure.microsoft.com/en-us/support/community/
- type: x-terms-of-service
  url: https://azure.microsoft.com/en-us/support/legal/
- type: x-twitter
  url: https://twitter.com/azure
- type: x-website
  url: https://azure.microsoft.com/en-us/services/automation/
- type: x-youtube
  url: https://www.youtube.com/user/windowsazure
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---