---
name: Beacon Application Services
description: Beacon is Oracle Platinum Partner Cloud Standard. We focus on the design,
  implementation and management of ERP systems.
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/beacon-application-services.yaml
tags:
- Professional Services
apis: []
x-common:
- type: x-website
  url: http://www.beaconservices.com
- type: x-about
  url: https://www.beaconservices.com/about-us
- type: x-blog
  url: https://www.beaconservices.com/blog
- type: x-blog
  url: https://www.beaconservices.com/blog/rss.xml
- type: x-blog
  url: https://www.beaconservices.com/blog/topic/beam-test
- type: x-blog
  url: https://www.beaconservices.com/blog/topic/peoplesoft
- type: x-blog
  url: https://www.beaconservices.com/blog/topic/beam
- type: x-blog
  url: https://www.beaconservices.com/blog/topic/higher-ed
- type: x-blog
  url: https://www.beaconservices.com/blog/topic/pum
- type: x-blog
  url: https://www.beaconservices.com/blog/topic/cloud-erp
- type: x-blog
  url: https://www.beaconservices.com/blog/topic/oracle
- type: x-careers
  url: https://www.beaconservices.com/beaconjobs
- type: x-contact
  url: https://www.beaconservices.com/contact-us
- type: x-customers
  url: https://www.beaconservices.com/customers
- type: x-facebook
  url: https://www.facebook.com/173808362748903
- type: x-linkedin
  url: https://www.linkedin.com/company/25763
- type: x-partner
  url: https://www.beaconservices.com/partners
- type: x-privacy
  url: https://www.beaconservices.com/privacy-policy
- type: x-twitter
  url: https://twitter.com/maudedan
- type: x-website
  url: https://www.beaconservices.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---