---
name: Build and configure a Linux-based media server
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "1531796"
url: https://raw.githubusercontent.com/api-network/organizations/main/build-and-configure-a-linuxbased-media-server.yaml
tags: []
apis: []
x-common:
- type: x-forum
  url: http://forum.havetheknowhow.com/
- type: x-website
  url: https://havetheknowhow.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---