---
name: CATIA V5 Automation
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/catia-v5-automation.yaml
tags:
- CATIA
apis: []
x-common:
- type: x-contact
  url: https://v5vb.wordpress.com/contact/
- type: x-developer
  url: http://developer.v5vb.wordpress.com
- type: x-press
  url: http://v5vb.wordpress.com/learning-series/
- type: x-press
  url: https://v5vb.wordpress.com/
- type: x-press
  url: https://v5vb.wordpress.com/about/
- type: x-press
  url: https://v5vb.wordpress.com/learning-series/
- type: x-press
  url: https://v5vb.wordpress.com/download/
- type: x-press
  url: https://v5vb.wordpress.com/page/2/
- type: x-press
  url: https://v5vb.wordpress.com/feed/
- type: x-press
  url: https://v5vb.wordpress.com/category/general/
- type: x-press
  url: https://v5vb.wordpress.com/category/content/system/
- type: x-press
  url: https://v5vb.wordpress.com/tag/activedocument/
- type: x-press
  url: https://v5vb.wordpress.com/tag/batch/
- type: x-press
  url: https://v5vb.wordpress.com/tag/catalog/
- type: x-press
  url: https://v5vb.wordpress.com/tag/center-of-gravity/
- type: x-press
  url: https://v5vb.wordpress.com/tag/code-organization/
- type: x-press
  url: https://v5vb.wordpress.com/tag/common-dialogs/
- type: x-press
  url: https://v5vb.wordpress.com/tag/compiler/
- type: x-press
  url: https://v5vb.wordpress.com/tag/custom-classes/
- type: x-press
  url: https://v5vb.wordpress.com/tag/debugging/
- type: x-press
  url: https://v5vb.wordpress.com/tag/declaring-variables/
- type: x-press
  url: https://v5vb.wordpress.com/tag/deleting/
- type: x-press
  url: https://v5vb.wordpress.com/tag/density/
- type: x-press
  url: https://v5vb.wordpress.com/tag/disassemble/
- type: x-press
  url: https://v5vb.wordpress.com/tag/download/
- type: x-press
  url: https://v5vb.wordpress.com/tag/drawing/
- type: x-press
  url: https://v5vb.wordpress.com/tag/errors/
- type: x-press
  url: https://v5vb.wordpress.com/tag/files/
- type: x-press
  url: https://v5vb.wordpress.com/tag/forms/
- type: x-press
  url: https://v5vb.wordpress.com/tag/formulas/
- type: x-press
  url: https://v5vb.wordpress.com/tag/geometry-types/
- type: x-press
  url: https://v5vb.wordpress.com/tag/getnametouseinrelation/
- type: x-press
  url: https://v5vb.wordpress.com/tag/hybridshapefactory/
- type: x-press
  url: https://v5vb.wordpress.com/tag/inertia/
- type: x-press
  url: https://v5vb.wordpress.com/tag/intellisense/
- type: x-press
  url: https://v5vb.wordpress.com/tag/license/
- type: x-press
  url: https://v5vb.wordpress.com/tag/macro-library/
- type: x-press
  url: https://v5vb.wordpress.com/tag/mass/
- type: x-press
  url: https://v5vb.wordpress.com/tag/measure/
- type: x-press
  url: https://v5vb.wordpress.com/tag/module/
- type: x-press
  url: https://v5vb.wordpress.com/tag/object-browser/
- type: x-press
  url: https://v5vb.wordpress.com/tag/parameters/
- type: x-press
  url: https://v5vb.wordpress.com/tag/parameter-sets/
- type: x-press
  url: https://v5vb.wordpress.com/tag/parent/
- type: x-press
  url: https://v5vb.wordpress.com/tag/part/
- type: x-press
  url: https://v5vb.wordpress.com/tag/performance/
- type: x-press
  url: https://v5vb.wordpress.com/tag/product/
- type: x-press
  url: https://v5vb.wordpress.com/tag/quick-info/
- type: x-press
  url: https://v5vb.wordpress.com/tag/recording/
- type: x-press
  url: https://v5vb.wordpress.com/tag/recursion/
- type: x-press
  url: https://v5vb.wordpress.com/tag/relations/
- type: x-press
  url: https://v5vb.wordpress.com/tag/rules/
- type: x-press
  url: https://v5vb.wordpress.com/tag/select-case/
- type: x-press
  url: https://v5vb.wordpress.com/tag/selection/
- type: x-press
  url: https://v5vb.wordpress.com/tag/startcommand/
- type: x-press
  url: https://v5vb.wordpress.com/tag/sublist/
- type: x-press
  url: https://v5vb.wordpress.com/tag/systemservice/
- type: x-press
  url: https://v5vb.wordpress.com/tag/text-file/
- type: x-press
  url: https://v5vb.wordpress.com/tag/toolbar/
- type: x-press
  url: https://v5vb.wordpress.com/tag/typename/
- type: x-press
  url: https://v5vb.wordpress.com/tag/userform/
- type: x-press
  url: https://v5vb.wordpress.com/tag/vba/
- type: x-press
  url: https://v5vb.wordpress.com/tag/winapi/
- type: x-press
  url: https://v5vb.wordpress.com/2012/03/
- type: x-press
  url: https://v5vb.wordpress.com/2010/10/
- type: x-press
  url: https://v5vb.wordpress.com/2010/09/
- type: x-press
  url: https://v5vb.wordpress.com/2010/07/
- type: x-press
  url: https://v5vb.wordpress.com/2010/06/
- type: x-press
  url: https://v5vb.wordpress.com/2010/05/
- type: x-press
  url: https://v5vb.wordpress.com/2010/04/
- type: x-press
  url: https://v5vb.wordpress.com/2010/03/
- type: x-press
  url: https://v5vb.wordpress.com/2010/02/
- type: x-press
  url: https://v5vb.wordpress.com/2010/01/
- type: x-press
  url: https://v5vb.wordpress.com/2009/12/
- type: x-press
  url: https://wordpress.com/?ref=footer_blog
- type: x-press
  url: https://wordpress.com/?ref=footer_website
- type: x-website
  url: https://v5vb.wordpress.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---