---
name: Centre for Intelligent Systems and their Applications
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "4618"
url: https://raw.githubusercontent.com/api-network/organizations/main/centre-for-intelligent-systems-and-their-applications.yaml
tags:
- University Of Edinburgh
apis: []
x-common:
- type: x-website
  url: https://www.cisa.informatics.ed.ac.uk
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---