---
name: Computricks Applications
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "576259"
url: https://raw.githubusercontent.com/api-network/organizations/main/computricks-applications.yaml
tags:
- Industry-Specific
apis: []
x-common:
- type: x-website
  url: https://css.itgo.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---