---
name: Configuration Data Services, Inc.
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/configuration-data-services-inc-.yaml
tags:
- Product Data Management
apis: []
x-common:
- type: x-developer
  url: http://developer.configdata.com
- type: x-website
  url: https://www.configdata.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---