---
name: Connected Safety and Security
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: ""
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/connected-safety-and-security.yaml
tags: []
apis: []
x-common:
- type: x-twitter
  url: https://twitter.com/CiscoPhySec
- type: x-website
  url: http://www.cisco.com/c/en/us/products/physical-security/index.html
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---