---
name: Cool Automation
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "947516"
url: https://raw.githubusercontent.com/api-network/organizations/main/cool-automation.yaml
tags:
- Products And Manufacturers
apis: []
x-common:
- type: x-about
  url: https://coolautomation.com/about/
- type: x-blog
  url: https://coolautomation.com/blog/
- type: x-contact
  url: https://coolautomation.com/contact-us/
- type: x-developer
  url: https://coolautomation.com/products/api/
- type: x-news
  url: https://coolautomation.com/news/
- type: x-support
  url: https://coolautomation.com/support/
- type: x-website
  url: https://www.coolautomation.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---