---
name: Corsec Security
description: Corsec guides companies through security certifications, helping them
  strengthen product security, improve corporate branding, & increase financial returns.
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "1314470"
url: https://raw.githubusercontent.com/api-network/organizations/main/corsec-security.yaml
tags:
- Companies
apis: []
x-common:
- type: x-about
  url: https://www.corsec.com/about-us/
- type: x-blog
  url: https://www.corsec.com/blog/
- type: x-contact
  url: https://www.corsec.com/contact-us/
- type: x-privacy
  url: https://www.corsec.com/privacy-policy/
- type: x-security
  url: https://www.corsec.com/security-compliance/
- type: x-support
  url: https://www.corsec.com/infrastructure-support/
- type: x-webinars
  url: https://www.corsec.com/webinars/
- type: x-website
  url: https://corsec.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---