---
name: Cosmin Buhu's Applications Site
description: Genuine products are not rare but people have to find them which are
  real are so that they may not be scammed through fake online sellers.
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/cosmin-buhus-applications-site.yaml
tags:
- Authors
apis: []
x-common:
- type: x-website
  url: https://www.easyvitools.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---