---
name: crowdin
description: Crowdin's localization management platform is a technology solution for
  your team. Translate and update content for your multilingual product with our cloud
  software.
image: http://kinlane-productions2.s3.amazonaws.com/api-evangelist-site/company/567_logo.png
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "7481682"
url: https://raw.githubusercontent.com/api-network/organizations/main/crowdin.yaml
tags:
- Translations
- Translations
- Translation Tool
- Platform
- Localization
- Languages
- Internationalization
- Have API
- Crowdin
- Collaborative
- API Provider
apis: []
x-common:
- type: x-website
  url: http://crowdin.com
- type: x-base
  url: https://api.crowdin.com/api/
- type: x-blog
  url: https://blog.crowdin.com/
- type: x-blog
  url: http://blog.crowdin.net/
- type: x-blog-rss
  url: http://feeds.feedburner.com/crowdin-blog
- type: x-contact
  url: https://crowdin.com/contacts
- type: x-crunchbase
  url: https://crunchbase.com/organization/crowdin
- type: x-crunchbase
  url: http://www.crunchbase.com/company/crowdin
- type: x-developers
  url: https://crowdin.com/page/api
- type: x-email
  url: support@crowdin.com
- type: x-email
  url: sales@crowdin.com
- type: x-facebook
  url: https://facebook.com/crowdin
- type: x-github
  url: https://github.com/crowdin
- type: x-integrations
  url: https://crowdin.com/page/integrations
- type: x-pricing
  url: https://crowdin.com/pricing
- type: x-pricing
  url: https://crowdin.com/pricing#annual
- type: x-privacy
  url: https://support.crowdin.com/privacy-policy/
- type: x-security
  url: https://support.crowdin.com/security/
- type: x-status
  url: http://status.crowdin.com/
- type: x-support
  url: https://support.crowdin.com/api/api-integration-setup/
- type: x-support
  url: https://support.crowdin.com
- type: x-support
  url: https://support.crowdin.com/company-description/
- type: x-terms-of-service
  url: https://support.crowdin.com/terms/
- type: x-twitter
  url: https://twitter.com/crowdin
- type: x-website
  url: https://crowdin.net/
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---