---
name: (CZ) Institute of Information Theory and Automation
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "32354"
url: https://raw.githubusercontent.com/api-network/organizations/main/cz-institute-of-information-theory-and-automation.yaml
tags:
- Czech Republic
apis: []
x-common:
- type: x-contact
  url: https://www.utia.cas.cz/contacts
- type: x-website
  url: https://www.utia.cas.cz
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---