---
name: Data Science Automation
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/data-science-automation.yaml
tags:
- Developers And Consultants
apis: []
x-common:
- type: x-website
  url: http://www.dsautomation.com
- type: x-about
  url: http://dsautomation.com/about-dsa/
- type: x-about
  url: http://dsautomation.com/about-dsa/purpose/
- type: x-about
  url: http://dsautomation.com/about-dsa/purpose/data/
- type: x-about
  url: http://dsautomation.com/about-dsa/purpose/products-2/
- type: x-about
  url: http://dsautomation.com/about-dsa/purpose/processes-2/
- type: x-about
  url: http://dsautomation.com/about-dsa/purpose/machines/
- type: x-about
  url: http://dsautomation.com/about-dsa/promise-2/
- type: x-about
  url: http://dsautomation.com/about-dsa/promise-2/values/
- type: x-about
  url: http://dsautomation.com/about-dsa/principles/
- type: x-about
  url: http://dsautomation.com/about-dsa/profiles/
- type: x-about
  url: http://dsautomation.com/about-dsa/clients/
- type: x-about
  url: http://dsautomation.com/about-dsa/locations/
- type: x-about
  url: http://www.dsautomation.com/about-dsa/
- type: x-blog
  url: http://dsautomation.com/resources/welcome-dsa-blog/
- type: x-careers
  url: http://dsautomation.com/about-dsa/careers-2/
- type: x-contact
  url: http://dsautomation.com/about-dsa/contact-dsa/
- type: x-developer
  url: http://developer.dsautomation.com
- type: x-news
  url: http://dsautomation.com/resources/news/
- type: x-news
  url: http://dsautomation.com/resources/newsletter/
- type: x-partner
  url: http://dsautomation.com/about-dsa/partners/
- type: x-twitter
  url: https://twitter.com/DSApgh
- type: x-website
  url: https://www.dsautomation.com
- type: x-youtube
  url: https://www.youtube.com/watch?v=PpVHJtnQRoI
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---