---
name: Duo Security
description: Duo???s Trusted Access platform verifies the identity of your users with
  two-factor authentication and security health of their devices before they connect
  to the apps you want them to access.
image: http://kinlane-productions2.s3.amazonaws.com/screen-capture-api/1050-duo-security.jpg
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "8"
x-alexaRank: "15395"
url: https://raw.githubusercontent.com/api-network/organizations/main/duo-security.yaml
tags:
- Security
- Security
- Have API
- Authentication
- API Service Provider
- API Provider
apis: []
x-common:
- type: x-about
  url: https://www.cisco.com/web/about/index.html
- type: x-base
  url: http://api.duosecurity.com
- type: x-blog
  url: http://blog.duosecurity.com
- type: x-blog-rss
  url: https://www.duosecurity.com/feed
- type: x-crunchbase
  url: http://www.crunchbase.com/company/duo-security
- type: x-crunchbase
  url: https://crunchbase.com/organization/duo-security
- type: x-developers
  url: https://www.duosecurity.com/api
- type: x-email
  url: support@duo.com
- type: x-email
  url: press@duo.com
- type: x-email
  url: privacy@duosecurity.com
- type: x-email
  url: mops@duosecurity.com
- type: x-email
  url: support@duosecurity.com
- type: x-email
  url: security@duosecurity.com
- type: x-email
  url: sally@duosecurity.com
- type: x-email
  url: eclat@duosecurity.com
- type: x-facebook
  url: https://www.facebook.com/duosec/
- type: x-instagram
  url: https://www.instagram.com/duosec/
- type: x-pricing
  url: https://duo.com/pricing
- type: x-security
  url: https://admin.duosecurity.com
- type: x-security
  url: https://admin.duosecurity.com/
- type: x-security
  url: https://www.linkedin.com/company/duo-security
- type: x-signup
  url: https://signup.duo.com/
- type: x-status
  url: https://status.duo.com
- type: x-terms-of-service
  url: https://www.cisco.com/c/en/us/about/legal/privacy.html
- type: x-twitter
  url: https://twitter.com/duosec
- type: x-website
  url: http://www.duosecurity.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---