---
name: eBaoCloud OpenAPI for Mobile BFF (Backends for Frontends)
description: not loading
image: https://s3.amazonaws.com/kinlane-productions2/api-evangelist-logos/api-evangelist-red-seal.png
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "0"
x-alexaRank: "20000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/ebaocloud-openapi-for-mobile-bff-backends-for-frontends.yaml
tags:
- Profile
- Have Swagger
- Have API Paths
apis: []
x-common:
- type: x-website
  url: http://eli.ebaocloud.com.cn
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---