---
name: environmentalleader.com
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "0"
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/environmentalleader-com.yaml
tags: []
apis: []
x-common:
- type: x-curated-source
  url: http://www.environmentalleader.com/2015/09/14/innovyze-water-management-system-delivers-real-time-visibility-of-non-revenue-water/
- type: x-website
  url: http://environmentalleader.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---