---
name: Environmental Protection Agency (EPA)
description: <p>The United States Environmental Protection Agency (EPA or sometimes
  USEPA) is an agency of the U.S. federal government which was created for the purpose
  of protecting human health and the environment by writing and enforcing regulations
  based on laws passed by Congress. The EPA was proposed by President Richard Nixon
  and began operation on December 2, 1970, after Nixon signed an executive order.
  The order establishing the EPA was ratified by committee hearings in the House and
  Senate. The agency is led by its Administrator, who is appointed by the president
  and approved by Congress. The current administrator is Gina McCarthy. The EPA is
  not a Cabinet department, but the administrator is normally given cabinet rank.</p>
image: http://kinlane-productions2.s3.amazonaws.com/api-evangelist-site/company/logos/280px-Environmental_Protection_Agency_logo.svg.png
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "9"
x-alexaRank: "6217"
url: https://raw.githubusercontent.com/api-network/organizations/main/environmental-protection-agency-epa.yaml
tags:
- Have API
- Federal Government
- Environment
- API Provider
apis: []
x-common:
- type: x-apis-json
  url: https://raw.githubusercontent.com/api-evangelist/1forge/master/apis.json
- type: x-about
  url: https://www.epa.gov/aboutepa/epas-administrator
- type: x-about
  url: https://www.epa.gov/aboutepa
- type: x-base-url
  url: iaspub.epa.gov
- type: x-careers
  url: https://www.epa.gov/careers
- type: x-contact
  url: https://www.epa.gov/home/forms/contact-us
- type: x-data
  url: https://www.epa.gov/enviro/data-downloads
- type: x-developer
  url: https://developer.epa.gov/portfolio/h2s-less-app/
- type: x-developer
  url: http://developer.epa.gov
- type: x-developer
  url: https://developer.epa.gov/
- type: x-developer
  url: https://developer.epa.gov/category/apis/
- type: x-developer
  url: https://developer.epa.gov/category/data/
- type: x-developer
  url: https://developer.epa.gov/question/
- type: x-developer
  url: https://developer.epa.gov/category/widgets/
- type: x-developer
  url: https://developer.epa.gov/author/admin/
- type: x-developer
  url: https://developer.epa.gov/portfolio/smokesense/
- type: x-developers
  url: http://www.epa.gov/developer/
- type: x-facebook
  url: https://www.facebook.com/EPA
- type: x-github
  url: https://github.com/USEPA
- type: x-instagram
  url: https://www.instagram.com/epagov
- type: x-news
  url: https://www.epa.gov/newsroom
- type: x-news
  url: https://www.epa.gov/newsroom/email-subscriptions
- type: x-open-source
  url: https://www.epa.gov/open
- type: x-privacy
  url: https://www.epa.gov/privacy
- type: x-twitter
  url: https://twitter.com/search/?q=%23EPAdata
- type: x-twitter
  url: https://twitter.com/epa
- type: x-website
  url: http://www.epa.gov
- type: x-wikipedia
  url: http://en.wikipedia.org/wiki/Environmental_Protection_Agency
- type: x-youtube
  url: https://www.youtube.com/user/USEPAgov
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---