---
name: Errata Security
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "0"
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/errata-security.yaml
tags:
- Security News
- Security
apis: []
x-common:
- type: x-blog-rss
  url: http://blog.erratasec.com/feeds/posts/default
- type: x-website
  url: http://blog.erratasec.com/
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---