---
name: Ervik.as - Application Delivery, Hyper-Converged, Cloud and Virtualization News
  &amp; Community
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "5519120"
url: https://raw.githubusercontent.com/api-network/organizations/main/ervik-as--application-delivery-hyperconverged-cloud-and-virtualization-news-amp-community.yaml
tags:
- Thin Clients
apis: []
x-common:
- type: x-website
  url: https://www.ervik.as
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---