---
name: Farsight Security
description: Farsight Security provides real-time actionable cyber security data solutions
  for Threat Intelligence, SOC and Incident Response teams
image: http://kinlane-productions2.s3.amazonaws.com/api-evangelist-site/company/logos/farsight-logo.svg
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "1272100"
url: https://raw.githubusercontent.com/api-network/organizations/main/farsight-security.yaml
tags:
- Security
- Have OpenAPI
- Have API Paths
- Have API
- API Service Provider
apis: []
x-common:
- type: x-blog
  url: https://www.farsightsecurity.com/Blog/
- type: x-blog-rss
  url: https://www.farsightsecurity.com/Blog/index.rss
- type: x-crunchbase
  url: https://crunchbase.com/organization/farsight-security
- type: x-email
  url: XXXXXXXXXXX@farsightsecurity.com
- type: x-email
  url: kburke@fsi.io
- type: x-email
  url: info@farsightsecurity.com
- type: x-email
  url: support@farsightsecurity.com
- type: x-email
  url: careers@farsightsecurity.com
- type: x-email
  url: sales@farsightsecurity.com
- type: x-email
  url: privacy@farsightsecurity.com
- type: x-github
  url: https://github.com/farsightsec
- type: x-security
  url: https://info.farsightsecurity.com/dfir-ebook
- type: x-security
  url: https://info.farsightsecurity.com/dnsdb-ebook
- type: x-security
  url: https://info.farsightsecurity.com/deloitte-case-study
- type: x-security
  url: https://blogs.infoblox.com/security/__trashed/
- type: x-twitter
  url: https://twitter.com/FarsightSecInc
- type: x-website
  url: https://www.farsightsecurity.com/
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---