---
name: Future+Automation
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "3122997"
url: https://raw.githubusercontent.com/api-network/organizations/main/futureautomation.yaml
tags:
- Products And Manufacturers
apis: []
x-common:
- type: x-website
  url: http://www.futureautomation.net
- type: x-facebook
  url: http://www.facebook.com/futureautomation
- type: x-instagram
  url: https://www.instagram.com/futureautomation
- type: x-linkedin
  url: http://www.linkedin.com/company/future-automation
- type: x-twitter
  url: http://www.twitter.com/automatedtv
- type: x-website
  url: https://www.futureautomation.co.uk
- type: x-youtube
  url: http://www.youtube.com/futureautomation
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---