---
name: 'GNUDE: GNU Development Environment'
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "433"
url: https://raw.githubusercontent.com/api-network/organizations/main/gnude-gnu-development-environment.yaml
tags:
- GNU Compiler Collection
apis: []
x-common:
- type: x-website
  url: https://gnude.sourceforge.net
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---