---
name: Google Alert - "Serverless"
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "5"
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/google-alert--serverless.yaml
tags:
- API Service Provider
- API Provider
apis: []
x-common:
- type: x-blog-rss
  url: https://www.google.com/alerts/feeds/16744132185142968751/12363542161977632900
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---