---
name: HIBO IT SECURITY
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "0"
x-alexaRank: "20000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/hibo-it-security.yaml
tags: []
apis: []
x-common:
- type: x-website
  url: http://www.hiboit.com
- type: x-twitter
  url: https://twitter.com/hiboit
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---