---
name: ILS Automation
description: Systems integrator specializing in bioreactor control systems, web-based
  SCADA software, and custom replacement controllers for cell culture & fermentation.
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/ils-automation.yaml
tags:
- Process
apis: []
x-common:
- type: x-about
  url: https://ils-automation.com/about/
- type: x-about
  url: https://ils-automation.com/about/history/
- type: x-about
  url: https://ils-automation.com/about/what-we-do/
- type: x-about
  url: https://ils-automation.com/about/faq/
- type: x-careers
  url: https://ils-automation.com/about/careers/
- type: x-case-studies
  url: https://ils-automation.com/case-studies/
- type: x-contact
  url: https://ils-automation.com/contact/
- type: x-developer
  url: http://developer.ils-automation.com
- type: x-events
  url: https://ils-automation.com/about/events/
- type: x-forum
  url: http://www.bluehostforum.com
- type: x-linkedin
  url: https://www.linkedin.com/company/ils-automation
- type: x-login
  url: http://www.bluehost.com/cgi-bin/cplogin
- type: x-news
  url: https://ils-automation.com/about/breaking-news/
- type: x-support
  url: https://ils-automation.com/support/
- type: x-support
  url: http://helpdesk.bluehost.com
- type: x-website
  url: https://ils-automation.com
- type: x-youtube
  url: http://www.youtube.com/c/Ilsautomationinc
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---