---
name: Inductive Automation
description: Inductive Automation provides SCADA software and industrial automation
  solutions. Ignition software is the universal platform for automation industry needs
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "145292"
url: https://raw.githubusercontent.com/api-network/organizations/main/inductive-automation.yaml
tags:
- Automation
apis: []
x-common:
- type: x-website
  url: http://www.inductiveautomation.com
- type: x-customers
  url: https://inductiveautomation.com/about/customers
- type: x-facebook
  url: https://www.facebook.com/InductiveAutomation/
- type: x-forum
  url: https://forum.inductiveautomation.com
- type: x-instagram
  url: https://www.instagram.com/inductiveautomation/?hl=en
- type: x-linkedin
  url: https://www.linkedin.com/company/inductive-automation
- type: x-support
  url: https://support.inductiveautomation.com/usermanuals
- type: x-twitter
  url: https://twitter.com/InductiveAuto
- type: x-website
  url: https://inductiveautomation.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---