---
name: Institute for Automation
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "51624"
url: https://raw.githubusercontent.com/api-network/organizations/main/institute-for-automation.yaml
tags:
- Research
apis: []
x-common:
- type: x-developer
  url: http://developer.automation.unileoben.ac.at
- type: x-website
  url: https://automation.unileoben.ac.at
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---