---
name: International Society for Computers and Their Applications
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/international-society-for-computers-and-their-applications.yaml
tags:
- Organizations
apis: []
x-common:
- type: x-developer
  url: http://developer.isca-hq.org
- type: x-website
  url: https://www.isca-hq.org
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---