---
name: "Io E\xB2 Io T API - to create end-user applications"
description: ""
image: https://s3.amazonaws.com/kinlane-productions2/api-evangelist-logos/api-evangelist-red-seal.png
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "2"
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/io-e-io-t-api--to-create-enduser-applications.yaml
tags:
- Profile
- Have Swagger
- Have API Paths
apis: []
x-common:
- type: x-website
  url: http://ijenko.net
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---