---
name: iPhone & iPad Application Development
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "1747368"
url: https://raw.githubusercontent.com/api-network/organizations/main/iphone-ipad-application-development.yaml
tags:
- Application Developers
apis: []
x-common:
- type: x-blog
  url: https://ethervision.net/blog/
- type: x-contact
  url: http://ethervision.net/#contact
- type: x-facebook
  url: https://www.facebook.com/ethervision/
- type: x-website
  url: https://ethervision.net
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---