---
name: Ittech Automation
description: 'ITTech provides PLC & DCS control based software tools and industrial
  automation services. For more info please call TelNo:+61423736059, email: tony@ittech-automation.com.au'
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/ittech-automation.yaml
tags:
- Rapid PLC Testing
- Rapid PLC Coding Tools
- Programmable Logic Testing
- PLC Testing Software
- PLC Testing
- PLC Programming Tools
- PLC Programming Software
- PLC Error Finding
- PLC Code Generation
- Logic Verification
- Industrial Automation Testing
- Easy PLC Programming
- Control Systems Tools
- Control Systems Testing
- Automation Functional Testing
- Automation
apis: []
x-common:
- type: x-developer
  url: http://developer.ittech-automation.com.au
- type: x-website
  url: https://www.ittech-automation.com.au
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---