---
name: JFig - Java Configuration Solution
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "429"
url: https://raw.githubusercontent.com/api-network/organizations/main/jfig--java-configuration-solution.yaml
tags:
- Build Tools
apis: []
x-common:
- type: x-website
  url: https://jfig.sourceforge.net
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---