---
name: JODE (Java Optimize and Decompile Environment)
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "429"
url: https://raw.githubusercontent.com/api-network/organizations/main/jode-java-optimize-and-decompile-environment.yaml
tags:
- Obfuscators
- Decompilers And Disassemblers
apis: []
x-common:
- type: x-website
  url: https://jode.sourceforge.net
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---