---
name: Journal of Graph Algorithms and Applications
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "2330645"
url: https://raw.githubusercontent.com/api-network/organizations/main/journal-of-graph-algorithms-and-applications.yaml
tags:
- Journals
apis: []
x-common:
- type: x-website
  url: https://jgaa.info
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---