---
name: 'Kiali: Service mesh observability and configuration'
description: ""
image: https://s3.amazonaws.com/kinlane-productions2/api-evangelist-logos/api-evangelist-red-seal.png
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "2178442"
url: https://raw.githubusercontent.com/api-network/organizations/main/kiali-service-mesh-observability-and-configuration.yaml
tags: []
apis: []
x-common:
- type: x-website
  url: http://kiali.io
- type: x-forum
  url: https://groups.google.com/forum/#!forum/kiali-users
- type: x-forum
  url: https://groups.google.com/forum/#!forum/kiali-dev
- type: x-github
  url: https://github.com/kiali
- type: x-privacy
  url: https://www.redhat.com/en/about/privacy-policy
- type: x-twitter
  url: https://twitter.com/kialiproject
- type: x-website
  url: http://www.kiali.io
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---