---
name: LORIA - Laboratoire Lorrain de Recherche en Informatique et ses Applications
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "204578"
url: https://raw.githubusercontent.com/api-network/organizations/main/loria--laboratoire-lorrain-de-recherche-en-informatique-et-ses-applications.yaml
tags:
- Research Institutes
apis: []
x-common:
- type: x-website
  url: http://www.loria.fr
- type: x-events
  url: https://www.loria.fr/events/categorie/seminars/
- type: x-twitter
  url: https://twitter.com/labo_Loria?ref_src=twsrc%5Etfw
- type: x-twitter
  url: https://twitter.com/@labo_Loria
- type: x-website
  url: https://www.loria.fr
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---