---
name: Mac OS X Automation
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "448307"
url: https://raw.githubusercontent.com/api-network/organizations/main/mac-os-x-automation.yaml
tags: []
apis: []
x-common:
- type: x-website
  url: https://www.macosxautomation.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---