---
name: Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.Tests.SampleApis
description: ""
image: https://s3.amazonaws.com/kinlane-productions2/api-evangelist-logos/api-evangelist-red-seal.png
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "0"
x-alexaRank: "20000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/microsoft-openapi-csharpannotations-documentgeneration-tests-sampleapis.yaml
tags:
- Have OpenAPI
- Have API Paths
apis: []
x-common:
- type: x-website
  url: http://myapi.sample.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---