---
name: mod_security
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "245067"
url: https://raw.githubusercontent.com/api-network/organizations/main/mod-security.yaml
tags:
- Modules
apis: []
x-common:
- type: x-twitter
  url: https://twitter.com/ModSecurity
- type: x-website
  url: https://www.modsecurity.org
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---