---
name: N.B. Automation
description: "Nous d\xE9veloppons et adaptons des solutions sp\xE9cialis\xE9es pour
  la tra\xE7abilit\xE9 de vos processus et pour le contr\xF4le de qualit\xE9 de votre
  production | NB Automation"
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/n-b--automation.yaml
tags:
- Automation
apis: []
x-common:
- type: x-contact
  url: https://www.nbautomation.com/contact/
- type: x-linkedin
  url: https://www.linkedin.com/company/nbautomation/
- type: x-website
  url: https://www.nbautomation.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---