---
name: Netlify
description: Deploy modern static websites with Netlify. Get CDN, Continuous deployment,
  1-click HTTPS, and all the services you need. Get started for free.
image: http://kinlane-productions2.s3.amazonaws.com/api-evangelist-site/company/logos/netlify-logo.jpg
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "21414"
url: https://raw.githubusercontent.com/api-network/organizations/main/netlify.yaml
tags:
- Websites
- Virtualizations
- Reviews
- Have API
- API Provider
- Aggregation
apis: []
x-common:
- type: x-blog
  url: https://www.netlify.com/blog/
- type: x-crunchbase
  url: https://crunchbase.com/organization/netlify
- type: x-developer
  url: http://developer.netlify.com
- type: x-developers
  url: https://www.netlify.com/docs/api/
- type: x-documentation
  url: https://docs.netlify.com/
- type: x-documentation
  url: https://docs.netlify.com/configure-builds/get-started/
- type: x-documentation
  url: https://docs.netlify.com/site-deploys/create-deploys/
- type: x-documentation
  url: https://docs.netlify.com/domains-https/custom-domains/
- type: x-documentation
  url: https://docs.netlify.com/functions/overview/
- type: x-documentation
  url: https://docs.netlify.com/large-media/transform-images/
- type: x-documentation
  url: https://docs.netlify.com/site-deploys/split-testing/
- type: x-documentation
  url: https://docs.netlify.com/visitor-access/identity/
- type: x-documentation
  url: https://docs.netlify.com
- type: x-email
  url: team@netlify.com
- type: x-email
  url: support@netlify.com
- type: x-github
  url: https://github.com/netlify
- type: x-press
  url: https://vuepress.vuejs.org/guide/markdown.html
- type: x-pricing
  url: https://www.netlify.com/pricing/
- type: x-signup
  url: https://app.netlify.com/signup
- type: x-status
  url: https://netlifystatus.com/
- type: x-twitter
  url: https://twitter.com/Netlify
- type: x-twitter
  url: https://twitter.com/youyuxi/status/952220999877058561
- type: x-twitter
  url: https://twitter.com/TruJared/status/969204723474673664
- type: x-twitter
  url: https://twitter.com/GoHugoIO
- type: x-twitter
  url: https://twitter.com/letsencrypt
- type: x-twitter
  url: https://twitter.com/alebaffa/status/965606177156382720
- type: x-webhooks
  url: https://www.netlify.com/docs/webhooks/
- type: x-website
  url: https://www.netlify.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---