---
name: 'OAR: On-Line Applications Research Corp.'
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/oar-online-applications-research-corp-.yaml
tags:
- RTEMS
apis: []
x-common:
- type: x-contact
  url: https://www.oarcorp.com/contact
- type: x-linkedin
  url: http://www.linkedin.com/company/oar
- type: x-twitter
  url: http://twitter.com/RTEMS_OAR
- type: x-website
  url: https://www.oarcorp.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---