---
name: OEE Automation
description: "OEE or Overall Equipment Effectiveness to give it its full title is
  a tool within the TPM (Total Productive Maintenance) method.\xC2\_ Development of
  TPM is attributed to Seiichi Nakajima of the Japan Institute of Plant Maintenance
  (JIPM) in Japan in the 1960\xE2\x80\x99s and 1970\xE2\x80\x99s. The origins of TPM
  in turn came from America | OEE Systems, Software, Articles & Resources"
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/oee-automation.yaml
tags:
- Software
- OEE Systems
- Automation
- Article And Resources
apis: []
x-common:
- type: x-press
  url: http://wordpress.org/
- type: x-website
  url: https://oeeautomation.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---