---
name: Offensive Security
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "25728"
url: https://raw.githubusercontent.com/api-network/organizations/main/offensive-security.yaml
tags:
- Exploits
apis: []
x-common:
- type: x-website
  url: https://www.offensive-security.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---