---
name: OnlineSecurity
description: OnlineSecurity Provides eDiscovery & Computer Forensics Services for
  Litigation Support.
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "7965313"
url: https://raw.githubusercontent.com/api-network/organizations/main/onlinesecurity.yaml
tags:
- United States
- Targeted Collections
- LOS
- Local Ediscovery
- Litigation Support
- Investigation
- Ediscovery Near Me
- EDiscovery
- Computer Forensics
- Cell Phone Forensics
- Angeles
apis: []
x-common:
- type: x-contact
  url: https://www.onlinesecurity.com/contact
- type: x-news
  url: https://www.onlinesecurity.com/news--publications-page
- type: x-news
  url: https://www.onlinesecurity.com/news--publications-5
- type: x-news
  url: https://www.onlinesecurity.com/news--publications-4
- type: x-security
  url: https://www.onlinesecurity.com/company-profile
- type: x-security
  url: https://www.onlinesecurity.com/professionals
- type: x-security
  url: https://www.onlinesecurity.com/projects
- type: x-security
  url: https://www.onlinesecurity.com/services
- type: x-security
  url: https://www.onlinesecurity.com/esi-consulting
- type: x-security
  url: https://www.onlinesecurity.com/expert-witness
- type: x-security
  url: https://www.onlinesecurity.com/targeted-collections
- type: x-security
  url: https://www.onlinesecurity.com/networkforensics
- type: x-security
  url: https://www.onlinesecurity.com/investigator
- type: x-security
  url: https://www.onlinesecurity.com/ediscovery
- type: x-security
  url: https://www.onlinesecurity.com/who-we-service
- type: x-security
  url: https://www.onlinesecurity.com/small-firm
- type: x-security
  url: https://www.onlinesecurity.com/medium-size-firm
- type: x-security
  url: https://www.onlinesecurity.com/large-size-firm
- type: x-security
  url: https://www.onlinesecurity.com/in-house-counsel
- type: x-security
  url: https://www.onlinesecurity.com/privacy-policy
- type: x-security
  url: https://www.onlinesecurity.com
- type: x-security
  url: https://www.onlinesecurity.com/about-us
- type: x-security
  url: http://www.linkedin.com/company/onlinesecurity
- type: x-website
  url: https://www.onlinesecurity.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---