---
name: Oracle Applications Users Group
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "3733504"
url: https://raw.githubusercontent.com/api-network/organizations/main/oracle-applications-users-group.yaml
tags:
- User Groups
apis: []
x-common:
- type: x-website
  url: http://oatug.org
- type: x-events
  url: https://www.oatug.org/events/calendar
- type: x-facebook
  url: https://www.facebook.com/OATUG1/
- type: x-twitter
  url: http://twitter.com/oatug1
- type: x-website
  url: https://www.oaug.org
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---