---
name: Oxford Journal of Cybersecurity
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "75293"
url: https://raw.githubusercontent.com/api-network/organizations/main/oxford-journal-of-cybersecurity.yaml
tags:
- No API
- Cybersecurity
apis: []
x-common:
- type: x-blog-rss
  url: http://cybersecurity.oxfordjournals.org/rss/current.xml
- type: x-press
  url: http://www.oxfordjournals.org/en/press/news.html
- type: x-press
  url: http://www.oxfordjournals.org/en/press/index.html
- type: x-blog
  url: http://blog.oup.com/
- type: x-careers
  url: https://globaljobs-careernetwork.oxfordjournals.org/
- type: x-careers
  url: http://global.oup.com/jobs
- type: x-facebook
  url: https://www.facebook.com/OUPAcademic
- type: x-privacy
  url: https://global.oup.com/privacy
- type: x-security
  url: http://mc.manuscriptcentral.com/cybersecurity
- type: x-security
  url: https://academic.oup.com/cybersecurity/pages/About
- type: x-twitter
  url: https://twitter.com/oxfordjournals
- type: x-twitter
  url: http://twitter.com/oupacademic
- type: x-website
  url: http://cybersecurity.oxfordjournals.org/
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---