---
name: Parallel Applications
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "289945"
url: https://raw.githubusercontent.com/api-network/organizations/main/parallel-applications.yaml
tags:
- FLTK
apis: []
x-common:
- type: x-developer
  url: http://developer.yaroslav-v.chat.ru
- type: x-website
  url: https://yaroslav-v.chat.ru
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---