---
name: proDAD
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "2764843"
url: https://raw.githubusercontent.com/api-network/organizations/main/prodad.yaml
tags:
- Retailers
apis: []
x-common:
- type: x-developer
  url: http://developer.prodad.de
- type: x-website
  url: https://www.prodad.de
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---