---
name: Producing Open Source Software - How to Run a Successful Free Software Project
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "3757527"
url: https://raw.githubusercontent.com/api-network/organizations/main/producing-open-source-software--how-to-run-a-successful-free-software-project.yaml
tags:
- Books
apis: []
x-common:
- type: x-developer
  url: http://developer.producingoss.com
- type: x-open-source
  url: http://opentechstrategies.com/
- type: x-website
  url: https://producingoss.com
- type: x-youtube
  url: http://youtube.com/watch?v=ZtYJoatnHb8
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---