---
name: ProductVid
description: Watch, Upload and share customer product review videos. Simply upload
  your product review videos or provide links to your existing review video online
  from sources such as YouTube.
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/productvid.yaml
tags:
- Videos
- Video Sharing
- Video Reviews
- Video
- Reviews
- Review
- Research
- Reports
- Report
- Rating
- Product Reviews
- Product Review
- Product Rating
- Product Information
- Product
- Information
- Consumer Reports
- Consumer
apis: []
x-common:
- type: x-login
  url: https://www.productvid.com/login
- type: x-signup
  url: https://www.productvid.com/signup
- type: x-support
  url: https://www.productvid.com/help
- type: x-website
  url: https://www.productvid.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---