---
name: Product Open Data
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "991096"
url: https://raw.githubusercontent.com/api-network/organizations/main/product-open-data.yaml
tags:
- Barcodes
apis: []
x-common:
- type: x-github
  url: https://github.com/okfn/opd-product-browser-web-new
- type: x-privacy
  url: http://okfn.org/privacy-policy/
- type: x-terms-of-service
  url: http://okfn.org/terms-of-use/
- type: x-website
  url: https://www.product-open-data.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---