---
name: Rapid Environment Editor
description: Rapid Environment Editor - freeware Windows environment variables editor
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "867372"
url: https://raw.githubusercontent.com/api-network/organizations/main/rapid-environment-editor.yaml
tags:
- System
apis: []
x-common:
- type: x-website
  url: http://www.rapidee.com
- type: x-twitter
  url: http://www.twitter.com/rapidee
- type: x-website
  url: https://www.rapidee.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---