---
name: REApplications
description: Commission tracking, property CRM, human resources, marketing - The complete
  back office solution for commercial real estate brokerages.
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "6894181"
url: https://raw.githubusercontent.com/api-network/organizations/main/reapplications.yaml
tags:
- REApplications
- Online Transaction Systems
apis: []
x-common:
- type: x-website
  url: http://www.costargroup.com
- type: x-careers
  url: http://costargroup.com/careers
- type: x-developer
  url: http://developer.reapplications.com
- type: x-facebook
  url: https://www.facebook.com/CoStarGroup
- type: x-linkedin
  url: https://www.linkedin.com/company/costar-group
- type: x-login
  url: https://gateway.costar.com/login
- type: x-news
  url: http://www.costargroup.com/costar-news
- type: x-twitter
  url: https://twitter.com/TheCoStarGroup
- type: x-website
  url: https://www.reapplications.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---