---
name: Research Center for Virtual Environments and Behavior
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "8241"
url: https://raw.githubusercontent.com/api-network/organizations/main/research-center-for-virtual-environments-and-behavior.yaml
tags:
- Research Projects
apis: []
x-common:
- type: x-privacy
  url: http://www.policy.ucsb.edu/privacy-notification
- type: x-terms-of-service
  url: http://www.policy.ucsb.edu/terms-of-use
- type: x-website
  url: https://www.recveb.ucsb.edu
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---