---
name: 'Rietta: Web Applications Where Security Matters'
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "372696"
url: https://raw.githubusercontent.com/api-network/organizations/main/rietta-web-applications-where-security-matters.yaml
tags:
- IP Utilities
apis: []
x-common:
- type: x-website
  url: https://www.rietta.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---