---
name: Rockwell Automation
description: Our official company page is a space to share your questions and ideas
  about our company and the manufacturing industry. In return, we'll share compelling,
  inspiring and humorous content that celebrates manufacturing, engineers and innovation.
  We hope ...
image: http://kinlane-productions2.s3.amazonaws.com/api-evangelist-site/company/logos/rockwell-automation.jpg
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "33145"
url: https://raw.githubusercontent.com/api-network/organizations/main/rockwell-automation.yaml
tags:
- Process
- No API Definition
- Industrial
- Have API
- Automation
apis: []
x-common:
- type: x-website
  url: http://www.rockwellautomation.com
- type: x-blog
  url: http://www.rockwellautomation.com/global/news/blog/overview.page
- type: x-blog-rss
  url: http://blog.emea.rockwellautomation.com/feed/
- type: x-crunchbase
  url: https://crunchbase.com/organization/rockwell-automation
- type: x-facebook
  url: https://www.facebook.com/ROKAutomation
- type: x-instagram
  url: https://www.instagram.com/rokautomation/
- type: x-linkedin
  url: https://www.linkedin.com/company/rockwell-automation
- type: x-press
  url: https://rok.auto/pressreleases
- type: x-support
  url: https://rockwellautomation.custhelp.com/
- type: x-twitter
  url: https://twitter.com/ROKAutomation
- type: x-twitter
  url: http://twitter.com/ROKAutomation
- type: x-website
  url: http://www.rockwellautomation.com/
- type: x-website
  url: https://www.rockwellautomation.com
- type: x-youtube
  url: http://www.youtube.com/rokautomation
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---