---
name: searchcloudapplications.techtarget.com
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "0"
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/searchcloudapplications-techtarget-com.yaml
tags: []
apis: []
x-common:
- type: x-curated-source
  url: http://searchcloudapplications.techtarget.com/news/450299207/Red-Hat-explains-its-acquisition-of-API-management-tools-maker-3scale
- type: x-website
  url: http://searchcloudapplications.techtarget.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---