---
name: Secure Application Development
description: SecAppDev is an intensive one-week course in secure application development.
  In-depth lectures and hands-on workshops take you on a deep-dive in today's security
  best practices.
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "5417427"
url: https://raw.githubusercontent.com/api-network/organizations/main/secure-application-development.yaml
tags:
- Security Course
- Security
- Secure Application Development
- Secappdev
- Sans
apis: []
x-common:
- type: x-twitter
  url: https://twitter.com/secappdev
- type: x-twitter
  url: https://twitter.com/SecAppDev?ref_src=twsrc%5Etfw
- type: x-website
  url: https://www.secappdev.org
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---