---
name: Security as a Service - Persistent Information security
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/security-as-a-service--persistent-information-security.yaml
tags:
- Software Protection And License Control
apis: []
x-common:
- type: x-website
  url: https://www.zafesoft.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---