---
name: Serverless
description: <p>The Serverless Framework is an application framework for building
  web, mobile and IoT applications powered by AWS Lambda, AWS API Gateway and in the
  future other Function as a Service providers.</p>
image: http://kinlane-productions2.s3.amazonaws.com/api-evangelist-site/company/logos/serverless-framework-logo.png
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "48539"
url: https://raw.githubusercontent.com/api-network/organizations/main/serverless.yaml
tags:
- Serverless
- No API
- API Service Provider
apis: []
x-common:
- type: x-website
  url: http://serverless.com
- type: x-blog
  url: http://blog.serverless.com/
- type: x-forum
  url: https://forum.serverless.com/
- type: x-github
  url: https://github.com/serverless/
- type: x-github
  url: https://github.com/serverless
- type: x-linkedin
  url: https://www.linkedin.com/company/serverless/
- type: x-terms-of-service
  url: https://dashboard.serverless.com/legal/terms
- type: x-terms-of-service
  url: https://dashboard.serverless.com/legal/privacy
- type: x-twitter
  url: https://twitter.com/goserverless
- type: x-twitter
  url: https://twitter.com/goserverless/
- type: x-website
  url: http://serverless.com/
- type: x-youtube
  url: https://www.youtube.com/watch?v=-Nf0ui3qP2E
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---