---
name: Shape Security
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "0"
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/shape-security.yaml
tags:
- Security
apis: []
x-common:
- type: x-website
  url: http://shapesecurity.com
- type: x-blog
  url: https://www.shapesecurity.com/blog.html
- type: x-twitter
  url: https://twitter.com/shapesecurity
- type: x-website
  url: https://www.shapesecurity.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---