---
name: "Single Page Application-Nextmeal | \u738B\u4ECB\u5FB7 , Danny Wang\u2019s ..."
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "0"
x-alexaRank: ""
url: https://raw.githubusercontent.com/api-network/organizations/main/single-page-applicationnextmeal----danny-wangs----.yaml
tags:
- Postman Doc Search
apis: []
x-common:
- type: x-postman-documentation
  url: https://documenter.getpostman.com/view/8897576/SW17UbmU
- type: x-postman-documentation
  url: https://documenter.getpostman.com/view/9952755/Szmb5eJb
- type: x-website
  url: http://www.cakeresume.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---