---
name: SlideME Community &amp; Mobile Application Marketplace for Android
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "182763"
url: https://raw.githubusercontent.com/api-network/organizations/main/slideme-community-amp-mobile-application-marketplace-for-android.yaml
tags:
- Markets
apis: []
x-common:
- type: x-website
  url: https://slideme.org
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---