---
name: Software Application and Information Solutions (pty) Ltd.
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "4818073"
url: https://raw.githubusercontent.com/api-network/organizations/main/software-application-and-information-solutions-pty-ltd-.yaml
tags:
- Consultants
apis: []
x-common:
- type: x-website
  url: http://www.sais-erp.com
- type: x-customers
  url: https://www.oracle.com/customers/index.html
- type: x-facebook
  url: https://www.facebook.com/pages/SAiS/179880495549550
- type: x-twitter
  url: https://twitter.com/sais_botswana
- type: x-website
  url: https://www.sais-erp.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---