---
name: "Speedment |\_Build Superfast Java Applications, Superfast"
description: ""
image: https://s3.amazonaws.com/kinlane-productions2/api-evangelist-logos/api-evangelist-red-seal.png
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "0"
x-alexaRank: "20000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/speedment-build-superfast-java-applications-superfast.yaml
tags: []
apis: []
x-common:
- type: x-website
  url: http://speedment.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---