---
name: SQL Security
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "2594386"
url: https://raw.githubusercontent.com/api-network/organizations/main/sql-security.yaml
tags:
- Microsoft SQL Server
apis: []
x-common:
- type: x-website
  url: https://www.sqlsecurity.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---