---
name: 'Suneido: Integrated Application Platform'
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "1650344"
url: https://raw.githubusercontent.com/api-network/organizations/main/suneido-integrated-application-platform.yaml
tags:
- Development Environments
apis: []
x-common:
- type: x-contact
  url: https://suneido.com/contact-us/
- type: x-developer
  url: http://developer.suneido.com
- type: x-feed
  url: https://suneido.com/an-rss-2-feed-creator/
- type: x-forum
  url: http://suneido.com/forums/
- type: x-forum
  url: https://suneido.com/forums/forum/announcements/
- type: x-forum
  url: https://suneido.com/forums/forum/cookbook/
- type: x-forum
  url: https://suneido.com/forums/forum/general/
- type: x-privacy
  url: https://suneido.com/privacy-statement/
- type: x-terms-of-service
  url: https://suneido.com/legal-statement/
- type: x-website
  url: https://www.suneido.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---