---
name: "swagger\u63A5\u53E3\u6587\u6863"
description: ""
image: https://s3.amazonaws.com/kinlane-productions2/api-evangelist-logos/api-evangelist-red-seal.png
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "2"
x-alexaRank: "20000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/swagger.yaml
tags:
- Have Swagger
- Have API Paths
apis: []
x-common:
- type: x-website
  url: http://10.0.0.50
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---