---
name: The Architecture of Open Source Applications
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "325073"
url: https://raw.githubusercontent.com/api-network/organizations/main/the-architecture-of-open-source-applications.yaml
tags:
- Books
apis: []
x-common:
- type: x-website
  url: https://www.aosabook.org
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---