---
name: The K Desktop Environment
description: KDE is an open community of friendly people who want to create a world
  in which everyone has control over their digital life and enjoys freedom and privacy.
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "38305"
url: https://raw.githubusercontent.com/api-network/organizations/main/the-k-desktop-environment.yaml
tags:
- KDE
apis: []
x-common:
- type: x-contact
  url: https://www.kde.org/contact/
- type: x-developer
  url: https://api.kde.org/
- type: x-developer
  url: http://developer.kde.org
- type: x-facebook
  url: https://www.facebook.com/kde/
- type: x-linkedin
  url: https://www.linkedin.com/company/29561/
- type: x-press
  url: https://www.kde.org/community/whatiskde/impressum
- type: x-twitter
  url: https://twitter.com/kdecommunity
- type: x-website
  url: https://www.kde.org
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---