---
name: Trace Security
description: TraceSecurity, Baton Rouge, Louisiana based cybersecurity company that
  provides cyber security and compliance services
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "1512536"
url: https://raw.githubusercontent.com/api-network/organizations/main/trace-security.yaml
tags:
- United States
- Riskmanagement
- Riskassessment
- Pentest
- NIST
- HITRUST
- HIPAA
- Cybersecurity
apis: []
x-common:
- type: x-case-studies
  url: https://www.tracesecurity.com/resources/case-studies
- type: x-contact
  url: https://www.tracesecurity.com/company/contact-us
- type: x-security
  url: https://www.tracesecurity.com/
- type: x-security
  url: https://www.tracesecurity.com/services-software
- type: x-security
  url: https://www.tracesecurity.com/compliance
- type: x-security
  url: https://www.tracesecurity.com/industries
- type: x-security
  url: https://www.tracesecurity.com/industries/banks
- type: x-security
  url: https://www.tracesecurity.com/industries/credit-unions
- type: x-security
  url: https://www.tracesecurity.com/industries/healthcare
- type: x-security
  url: https://www.tracesecurity.com/company
- type: x-security
  url: https://www.tracesecurity.com/company/careers
- type: x-security
  url: https://www.tracesecurity.com/company/leadership
- type: x-security
  url: https://www.tracesecurity.com/resources
- type: x-security
  url: https://www.tracesecurity.com/resources/infographics
- type: x-security
  url: https://www.tracesecurity.com/phishing
- type: x-security
  url: https://www.tracesecurity.com/blog
- type: x-security
  url: https://csat.tracesecurity.com/register
- type: x-security
  url: https://www.linkedin.com/company/tracesecurity/
- type: x-security
  url: https://cso.tracesecurity.com/
- type: x-security
  url: https://insight.tracesecurity.com/login
- type: x-webinars
  url: https://www.tracesecurity.com/resources/webinars
- type: x-website
  url: https://www.tracesecurity.com
- type: x-white-papers
  url: https://www.tracesecurity.com/resources/whitepapers
- type: x-youtube
  url: https://www.youtube.com/user/TraceSecurityVideo
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---