---
name: Traefik
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "146202"
url: https://raw.githubusercontent.com/api-network/organizations/main/traefik.yaml
tags: []
apis: []
x-common:
- type: x-website
  url: https://containo.us
- type: x-blog
  url: https://containo.us/tag/blog/
- type: x-contact
  url: https://info.containo.us/contact-sales
- type: x-documentation
  url: https://docs.containo.us/
- type: x-documentation
  url: https://docs.traefik.io/
- type: x-github
  url: https://github.com/containous/traefik/releases
- type: x-github
  url: https://github.com/containous/traefik/
- type: x-linkedin
  url: https://www.linkedin.com/company/containous/
- type: x-support
  url: https://support.containo.us
- type: x-twitter
  url: https://twitter.com/containous
- type: x-website
  url: https://traefik.io/
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---