---
name: Training Planet
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "8264560"
url: https://raw.githubusercontent.com/api-network/organizations/main/training-planet.yaml
tags:
- Certification
apis: []
x-common:
- type: x-website
  url: https://www.trainingplanet.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---