---
name: Trifork Enterprise Application Server
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "757979"
url: https://raw.githubusercontent.com/api-network/organizations/main/trifork-enterprise-application-server.yaml
tags:
- Application Servers
apis: []
x-common:
- type: x-blog
  url: http://blog.trifork.com
- type: x-contact
  url: https://trifork.com/contact/
- type: x-contact
  url: http://trifork.com/contact/
- type: x-developer
  url: http://developer.trifork.com
- type: x-documentation
  url: https://docs.atlassian.com/jira/jcore-docs-084/
- type: x-events
  url: https://trifork.com/events/
- type: x-facebook
  url: https://www.facebook.com/Trifork/
- type: x-instagram
  url: https://www.instagram.com/trifork_stories/
- type: x-linkedin
  url: https://www.linkedin.com/company/trifork/
- type: x-partner
  url: https://trifork.com/partners/
- type: x-privacy
  url: https://trifork.com/privacy-policy/
- type: x-website
  url: https://www.trifork.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---