---
name: Vertex Flow OpenAPI - Vertex Flow 2020 tuotedokumentaatio
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "0"
x-alexaRank: ""
url: https://raw.githubusercontent.com/api-network/organizations/main/vertex-flow-openapi--vertex-flow-2020-tuotedokumentaatio.yaml
tags:
- Postman Doc Search
- New
apis: []
x-common:
- type: x-postman-documentation
  url: https://documenter.getpostman.com/view/3502772/SW11Wdg9
- type: x-website
  url: http://kb.vertex.fi
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---