---
name: Visual Servo Automation
description: "Visual Show Automation (VSA) is the first visual \n\t\tsolution to servo
  control and automation using the Mini-SSC, SV203, SMI, Parallax/Propeller, \n\t\tParallel
  Port, DMX and DMX512."
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/visual-servo-automation.yaml
tags:
- VSA
- Visual Servo Automation
- Sv203
- Ssc
- Servos
- Servo Control
- Servo
- Seetron
- Robots
- Robotics
- Robot
- Propeller
- Pontech
- Parallax
- Mini-ssc
- Mini Ssc
- Mini
- DMX512
- DMX
- Controling Servos
- Control
- Automation
- Animatronics
- Animatronic
apis: []
x-common:
- type: x-website
  url: https://www.brookshiresoftware.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---