---
name: Voiyager Dynamic Application Discovery
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/voiyager-dynamic-application-discovery.yaml
tags:
- VoiceXML
apis: []
x-common:
- type: x-developer
  url: http://developer.voiyager.com
- type: x-website
  url: https://www.voiyager.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---