---
name: Water and Environmental Hub API
description: ""
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "1000000"
url: https://raw.githubusercontent.com/api-network/organizations/main/water-and-environmental-hub-api.yaml
tags: []
apis: []
x-common:
- type: x-website
  url: http://www.waterenvironmentalhub.ca
- type: x-about
  url: http://www.waterenvironmentalhub.ca/about-us/
- type: x-blog
  url: http://www.waterenvironmentalhub.ca/blog/
- type: x-blog
  url: http://www.waterenvironmentalhub.ca/category/blog/
- type: x-contact
  url: http://www.waterenvironmentalhub.ca/contact-us/
- type: x-feed
  url: http://www.waterenvironmentalhub.ca/feed/
- type: x-feed
  url: http://www.waterenvironmentalhub.ca/comments/feed/
- type: x-login
  url: http://www.waterenvironmentalhub.ca/wp-login.php
- type: x-press
  url: https://wordpress.org/
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---