---
name: XML Config Object
description: 'ApoliSoft products: MCataloguer, Font Fitting Room, XML Config Object'
image: ""
created: "2021-02-04"
modified: "2021-02-04"
specificationVersion: "0.14"
x-rank: "7"
x-alexaRank: "9280508"
url: https://raw.githubusercontent.com/api-network/organizations/main/xml-config-object.yaml
tags:
- XML
- Uninstalled
- Object
- Font Preview
- Font Manager
- Config
- Cataloguer
- Cataloging
- Catalog
apis: []
x-common:
- type: x-support
  url: http://www.apolisoft.com/support.php
- type: x-website
  url: https://www.apolisoft.com
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com
---